name: covidstats
version: 5.0.1
summary: Italian pandemic data
description: Show italian pandemic data

confinement: strict
base: core18
grade: stable

slots:
  dbus-covidstats: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.fvalle1.covidstats # adjust accordingly to your app name and
    
apps:
  covidstats:
    command: covidstats
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-covidstats
parts:
  covidstats:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
