name: Dart Build web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
    - uses: jddeep/Flutter-Runner@1.2.0
    - name: Run tests
    - run: flutter pub get
    - run: flutter build web
