name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

     steps:
     - name: Install dependencies
       uses: actions/checkout@v2
     - name: Install dependencies
       uses: steebchen/flutter@v1.1.0
     - name: Run tests
       run: flutter pub get
     - run: flutter pub run test
