name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
     - name: Install dependencies
       uses: actions/checkout@v2
     - uses: steebchen/flutter@v1.1.0
       with:
        args: pub get
     - uses: steebchen/flutter@v1.1.0
       with:
        args: pub test
